[project]
name = "maat-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.15.1",
]

[project.scripts]
mscripts = "main:main"

